name: asr_test
channels:
- conda-forge
- huggingface
- nvidia
- pytorch
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- aiohappyeyeballs=2.4.4
- aiohttp=3.11.9
- aiosignal=1.3.1
- aom=3.5.0
- async-timeout=4.0.3
- attrs=23.2.0
- audioread=3.0.1
- aws-c-auth=0.7.22
- aws-c-cal=0.7.1
- aws-c-common=0.9.23
- aws-c-compression=0.2.18
- aws-c-event-stream=0.4.2
- aws-c-http=0.8.2
- aws-c-io=0.14.10
- aws-c-mqtt=0.10.4
- aws-c-s3=0.6.0
- aws-c-sdkutils=0.1.16
- aws-checksums=0.1.18
- aws-crt-cpp=0.27.3
- aws-sdk-cpp=1.11.329
- azure-core-cpp=1.13.0
- azure-identity-cpp=1.8.0
- azure-storage-blobs-cpp=12.12.0
- azure-storage-common-cpp=12.7.0
- azure-storage-files-datalake-cpp=12.11.0
- blas=1.0
- brotli=1.1.0
- brotli-bin=1.1.0
- brotli-python=1.1.0
- bzip2=1.0.8
- c-ares=1.28.1
- ca-certificates=2024.2.2
- certifi=2024.2.2
- cffi=1.17.1
- charset-normalizer=3.3.2
- click=8.1.7
- colorama=0.4.6
- contourpy=1.3.1
- cpython=3.11.11
- cuda-cudart=11.8.89
- cuda-cupti=11.8.87
- cuda-libraries=11.8.0
- cuda-nvrtc=11.8.89
- cuda-nvtx=11.8.86
- cuda-runtime=11.8.0
- cuda-version=11.8
- cudatoolkit=11.8.0
- cudnn=9.3.0.75
- cycler=0.12.1
- dataclasses=0.8
- datasets=2.18.0
- decorator=5.1.1
- dill=0.3.9
- ffmpeg=5.1.2
- filelock=3.13.4
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.15.0
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.55.2
- freetype=2.12.1
- frozenlist=1.5.0
- fsspec=2024.3.1
- gettext=0.22.5
- gettext-tools=0.22.5
- gflags=2.2.2
- glog=0.7.1
- gmp=6.3.0
- gmpy2=2.1.5
- gnutls=3.7.9
- huggingface_hub=0.22.2
- icu=75.1
- idna=3.7
- importlib-metadata=8.5.0
- jinja2=3.1.3
- jiwer=3.0.5
- joblib=1.4.2
- jpeg=9e
- kaldi=5.5.1112
- kernel-headers_linux-64=3.10.0
- keyutils=1.6.1
- kiwisolver=1.4.7
- krb5=1.21.2
- lame=3.100
- lazy-loader=0.4
- lazy_loader=0.4
- lcms2=2.15
- ld_impl_linux-64=2.40
- lerc=4.0.0
- libabseil=20240116.2
- libarrow=17.0.0
- libarrow-acero=17.0.0
- libarrow-dataset=17.0.0
- libarrow-flight=17.0.0
- libarrow-flight-sql=17.0.0
- libarrow-gandiva=17.0.0
- libarrow-substrait=17.0.0
- libasprintf=0.22.5
- libasprintf-devel=0.22.5
- libblas=3.9.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcblas=3.9.0
- libcrc32c=1.1.2
- libcublas=11.11.3.6
- libcufft=10.9.0.58
- libcufile=1.9.1.3
- libcurand=10.3.5.147
- libcurl=8.8.0
- libcusolver=11.4.1.48
- libcusparse=11.7.5.86
- libdeflate=1.17
- libdrm=2.4.124
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.12
- libexpat=2.6.4
- libffi=3.4.2
- libflac=1.4.3
- libgcc=14.2.0
- libgcc-ng=14.2.0
- libgettextpo=0.22.5
- libgettextpo-devel=0.22.5
- libgfortran=14.2.0
- libgfortran-ng=14.2.0
- libgfortran5=14.2.0
- libgomp=14.2.0
- libgoogle-cloud=2.26.0
- libgoogle-cloud-storage=2.26.0
- libgrpc=1.62.2
- libhwloc=2.10.0
- libiconv=1.17
- libidn2=2.3.7
- libjpeg-turbo=2.0.0
- liblapack=3.9.0
- liblapacke=3.9.0
- libllvm14=14.0.6
- libllvm16=16.0.6
- libllvm17=17.0.6
- liblzma=5.6.3
- libmagma=2.8.0
- libmagma_sparse=2.8.0
- libnghttp2=1.58.0
- libnl=3.9.0
- libnpp=11.8.0.86
- libnsl=2.0.1
- libnvjpeg=11.9.0.86
- libogg=1.3.5
- libopenblas=0.3.27
- libopus=1.3.1
- libparquet=17.0.0
- libpciaccess=0.18
- libpng=1.6.44
- libprotobuf=4.25.3
- libre2-11=2023.09.01
- librosa=0.10.2
- libsndfile=1.2.2
- libsqlite=3.47.0
- libssh2=1.11.1
- libstdcxx=14.2.0
- libstdcxx-ng=13.2.0
- libtasn1=4.19.0
- libthrift=0.19.0
- libtiff=4.5.0
- libtorch=2.4.1
- libunistring=0.9.10
- libutf8proc=2.8.0
- libuuid=2.38.1
- libuv=1.49.2
- libva=2.18.0
- libvorbis=1.3.7
- libvpx=1.11.0
- libwebp-base=1.4.0
- libxcb=1.13
- libxcrypt=4.4.36
- libxml2=2.13.5
- libzlib=1.3.1
- llvm-openmp=19.1.5
- llvmlite=0.43.0
- lz4-c=1.9.4
- markupsafe=3.0.2
- matplotlib-base=3.9.3
- mkl=2023.2.0
- mpc=1.3.1
- mpfr=4.2.1
- mpg123=1.32.6
- mpmath=1.3.0
- msgpack-python=1.1.0
- multidict=6.1.0
- multiprocess=0.70.17
- munkres=1.1.4
- nccl=2.23.4.1
- ncurses=6.5
- nettle=3.9.1
- networkx=3.2
- numba=0.60.0
- numpy=2.0.2
- openfst=1.8.3
- openh264=2.3.1
- openjpeg=2.5.0
- openssl=3.4.0
- orc=2.0.1
- p11-kit=0.24.1
- packaging=24.0
- pandas=2.2.3
- pillow=9.4.0
- pip=24.0
- platformdirs=4.3.6
- pooch=1.8.2
- propcache=0.2.1
- pthread-stubs=0.4
- pyarrow=17.0.0
- pyarrow-core=17.0.0
- pyarrow-hotfix=0.6
- pycparser=2.22
- pyparsing=3.2.0
- pysocks=1.7.1
- pysoundfile=0.12.1
- python=3.11.11
- python-dateutil=2.9.0
- python-tzdata=2024.1
- python-xxhash=3.5.0
- python_abi=3.11
- pytorch=2.4.1
- pytorch-cuda=11.8
- pytorch-mutex=1.0
- pytz=2024.1
- pyyaml=6.0.2
- qhull=2020.2
- rapidfuzz=3.10.1
- rdma-core=51.0
- re2=2023.09.01
- readline=8.2
- requests=2.31.0
- s2n=1.4.17
- scikit-learn=1.5.2
- scipy=1.14.1
- setuptools=69.5.1
- six=1.16.0
- sleef=3.7
- snappy=1.2.1
- soxr=0.1.3
- soxr-python=0.5.0.post1
- svt-av1=1.4.1
- sympy=1.13.3
- sysroot_linux-64=2.17
- tbb=2021.12.0
- threadpoolctl=3.5.0
- tk=8.6.13
- torchaudio=2.4.1
- tornado=6.4.2
- tqdm=4.66.2
- typing-extensions=4.11.0
- typing_extensions=4.11.0
- tzdata=2024a
- ucx=1.15.0
- unicodedata2=15.1.0
- urllib3=2.2.1
- wheel=0.43.0
- x264=1!164.3095
- x265=3.5
- xorg-fixesproto=5.0
- xorg-kbproto=1.0.7
- xorg-libx11=1.8.4
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxfixes=5.0.3
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xxhash=0.8.2
- xz=5.2.6
- yaml=0.2.5
- yarl=1.18.3
- zipp=3.21.0
- zlib=1.3.1
- zstd=1.5.6

